### ISSUE TITLE
Move to `examples/` dir

### ISSUE THREAD

**Issue by bpmct** [coder/packages#16]
Move this repo into the Coder project with `examples/`. Let's create separate repos for Railway, Heroku, etc.

**Comment by bpmct** [comment]
I don't plan on doing this in the next few months, but it is planned.

**Comment by matifali** [comment]
I have a few suggestions,

1. Create separate repos under https://github.com/coder
 like GitHub does for workspaces

See: https://github.com/orgs/github/repositories?q=codespaces&type=source&language=&sort=


2. Instead of creating different repos, we can put each in a different branch.

 heroku --> branch heroku

 railway --> branch railway

I prefer 1st option.

**Comment by matifali** [comment]
We do not need a repo or directory for railway anymore. See #98
